services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap
    command:
      - zap.sh
      - -daemon
      - -host
      - 0.0.0.0
      - -port
      - "8080"
      - -config
      - api.disablekey=false
      - -config
      - api.key=${ZAP_API_KEY}
      - -config
      - api.addrs.addr.name=.*
      - -config
      - api.addrs.addr.regex=true
    ports:
      - "8080:8080"
    networks:
      - my-net

  pyapp:
    build: ./
    container_name: pyapp
    env_file:
      - .env
    depends_on:
      - zap
    networks:
      - my-net
    ports:
      - "5000:5000"
    volumes:
      - "./reports:/app/reports"
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - my-net
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

networks:
  my-net:
    driver: bridge
